### ISSUE TITLE
How to use the model to visualize a video like the slowfast repo ?

### ISSUE THREAD

**Issue by dongxiaolong** [facebookresearch/MeMViT#1]
When I use the model like Slowfast repo, I use the run_net.py to inference on a video. I get a error 
```
[12/07 09:22:26][INFO] predictor.py: 177: Initialized Detectron2 Object Detection Model.
[12/07 09:22:26][INFO] checkpoint.py: 152: [Checkpointer] Loading from detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl ...
[12/07 09:22:26][INFO] file_io.py: 798: URL https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl cached in /home/xiaolong/.torch/iopath_cache/detectron2/COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl
[12/07 09:22:27][INFO] detection_checkpoint.py:  65: Reading a file from 'Detectron2 Model Zoo'
[12/07 09:22:27][INFO] predictor.py:  44: Start loading model weights.
[12/07 09:22:27][INFO] checkpoint.py: 221: Loading network weights from /home/xiaolong/SlowFast/slowfast/pretrain_model/MeMViT_16L_16x4_K400pt.pyth.
[12/07 09:22:27][INFO] predictor.py:  46: Finish loading model weights
/home/xiaolong/miniconda3/envs/slowfast/lib/python3.8/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1656352465323/work/aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
0it [00:12, ?it/s]
Traceback (most recent call last):
  File "tools_MeMvit/run_net.py", line 43, in <module>
    main()
  File "tools_MeMvit/run_net.py", line 39, in main
    demo(cfg)
  File "/home/xiaolong/SlowFast/slowfast/tools_MeMvit/demo_net.py", line 114, in demo
    for task in tqdm.tqdm(run_demo(cfg, frame_provider)):
  File "/home/xiaolong/miniconda3/envs/slowfast/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/xiaolong/SlowFast/slowfast/tools_MeMvit/demo_net.py", line 79, in run_demo
    model.put(task)
  File "/home/xiaolong/SlowFast/slowfast/memvit/visualization/predictor.py", line 138, in put
    task = self.predictor(task)
  File "/home/xiaolong/SlowFast/slowfast/memvit/visualization/predictor.py", line 100, in __call__
    preds = self.model(inputs, bboxes)
  File "/home/xiaolong/miniconda3/envs/slowfast/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xiaolong/SlowFast/slowfast/memvit/models/video_model_builder.py", line 1110, in forward
    x, thw = blk(x, thw, cur_selection, video_names)
  File "/home/xiaolong/miniconda3/envs/slowfast/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xiaolong/SlowFast/slowfast/memvit/models/attention.py", line 930, in forward
    x_block, thw_shape_new = self.attn(
  File "/home/xiaolong/miniconda3/envs/slowfast/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xiaolong/SlowFast/slowfast/memvit/models/attention.py", line 600, in forward
    q, q_shape = attention_pool(
  File "/home/xiaolong/SlowFast/slowfast/memvit/models/attention.py", line 35, in attention_pool
    tensor.reshape(B * N, T, H, W, C).permute(0, 4, 1, 2, 3).contiguous()
**RuntimeError: shape '[1, 8, 82, 56, 96]' is invalid for input of size 3569664**
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/xiaolong/miniconda3/envs/slowfast/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
Process _VisWorker-1:
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/xiaolong/miniconda3/envs/slowfast/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/home/xiaolong/miniconda3/envs/slowfast/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/home/xiaolong/miniconda3/envs/slowfast/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/xiaolong/miniconda3/envs/slowfast/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/xiaolong/miniconda3/envs/slowfast/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/home/xiaolong/miniconda3/envs/slowfast/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/home/xiaolong/miniconda3/envs/slowfast/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```
I check the slowfast repo and this repo. I didn't see any difference in attention.py at attention_pool function.
What can i do to fix the problem ?

**Comment by chaoyuaw** [comment]
Hi @dongxiaolong, Thanks for using MeMVit. 

Can you please clarify where you got the `demo_net.py` file from? MeMViT does not support `demo_net` as of now and does not have a `demo_net.py` file. If you'd like to implement the new functionality based on SlowFast repo's `demo_net.py`, I recommend taking a look at `test_net.py` and and other differences between MeMViT and SlowFast. Thanks!

**Comment by dongxiaolong** [comment]
> Hi @dongxiaolong, Thanks for using MeMVit.
> 
> Can you please clarify where you got the `demo_net.py` file from? MeMViT does not support `demo_net` as of now and does not have a `demo_net.py` file. If you'd like to implement the new functionality based on SlowFast repo's `demo_net.py`, I recommend taking a look at `test_net.py` and and other differences between MeMViT and SlowFast. Thanks!

I got the `demo_net.py` from original slowfast repo. And I modified the slowfast module to memvit module. I will try the steps you suggested. Thank you. Could you merge Memvit to the original slowfast repo? more people will know this job and solve these problems.

**Comment by faezehprb** [comment]
> > Hi @dongxiaolong, Thanks for using MeMVit.
> > Can you please clarify where you got the `demo_net.py` file from? MeMViT does not support `demo_net` as of now and does not have a `demo_net.py` file. If you'd like to implement the new functionality based on SlowFast repo's `demo_net.py`, I recommend taking a look at `test_net.py` and and other differences between MeMViT and SlowFast. Thanks!
> 
> I got the `demo_net.py` from original slowfast repo. And I modified the slowfast module to memvit module. I will try the steps you suggested. Thank you. Could you merge Memvit to the original slowfast repo? more people will know this job and solve these problems.

Have you done this?
If yes would you mind sharing it with us?
